development:
  adapter: postgresql
  encoding: unicode
  database: prima_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: prima_test
  pool: 5
  username:
  password:
